### ISSUE TITLE
I want to contribute to silkworm-rs.

### ISSUE THREAD

**Issue by superseeker13** [silkworm-rs/silkworm#1]
I am relatively new to Rust, having used Java most of my career but am able to hold my own and wish to contribute.  I am going to fork the repo and start to look around.  If there is anything I can help with please let me know.

**Comment by ghost** [comment]
Hello @superseeker13 ! Thanks for your interest!

It's still a bit early before we can actually accept general code contributions, though. Currently the project is still in the initial development phase, so there is a lot of uncertainly. However, there are still ways to contribute if you're interested!

## Adding more test cases to `silkworm-syn`

Currently, the parser part is considered complete: it should be able to parse any Yarn 1.1 code thrown at it, and it's considered a bug if it can't. If you have short snippets of code that cover more edge cases of the parser, you may add them to the `test` modules inside the modules in `silkworm_syn/src/parse`.

It's also good to add integration tests in a [`tests` directory][int-tests] for longer tests.

## Adding proper tests for the lexer

Currently, the `it_works_at_all` test only ensures that the code lexes *at all*, but not that the lexing is correct. You can try adding proper tests to it, preferably as integration tests in a [`tests` directory][int-tests] that reads code and reference tokens from text files. Note that due to the complexity of the Yarn language, code sometimes need to be re-interpreted in the parser, so testing is a bit tricky.

You may use `serde` for serialization and deserialization of the tokens.

## Fixing bugs

And, of course, if you find any bugs while adding tests, feel free to try and fix them!

## Create a source formatting tool using `silkworm-syn`

This could become the first practical use case for the silkworm project! We may use silkworm-syn to parse source, refine it, and then pretty-print the AST if there were no parse errors. Pretty printing needs to be implemented separately however. This can't be done *right now* because we still need #6, but a barebones solution should be fairly straightforward!

[int-tests]: https://doc.rust-lang.org/cargo/guide/tests.html

**Comment by superseeker13** [comment]
Alright, I will see what I can do.
